CREATE TABLE lists (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE todos (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT false,
  list_id INTEGER NOT NULL REFERENCES lists (id) ON DELETE CASCADE
);